on: [push]

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: jose
          paper-path: jose/paper.md
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: paper
          path: jose/paper.pdf
      - name: Commit PDF
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add jose/paper.pdf
          git commit -m "Automatically updated paper PDF"
          git push
